##############################################################################
# GRAFANA - Data Sources Provisioning
##############################################################################

apiVersion: 1

datasources:
  ##########################################################################
  # PROMETHEUS (Metrics)
  ##########################################################################
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: true
    jsonData:
      timeInterval: "30s"
      queryTimeout: "60s"
      httpMethod: "POST"

  ##########################################################################
  # LOKI (Logs)
  ##########################################################################
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    version: 1
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: Prometheus
          matcherRegex: 'traceID=(\\w+)'
          name: TraceID
          url: "$${__value.raw}"

  ##########################################################################
  # PROMETHEUS ALERTMANAGER (Alerts - Optional)
  ##########################################################################
  # - name: Alertmanager
  #   type: alertmanager
  #   access: proxy
  #   url: http://alertmanager:9093
  #   version: 1
  #   editable: true
  #   jsonData:
  #     implementation: 'prometheus'

deleteDatasources:
  - name: TestData DB
    orgId: 1
